WCCILdata    (0), 2020.02.16 11:00:12.699, SYS,  INFO,        1, Manager Start, PROJ, myGettingStarted, V 3.16 - 3.16   platform Windows AMD64 linked at Sep 20 2019 10:16:47 (726e8f60c5d)
WCCILdata    (0), 2020.02.16 11:00:12.843, SYS,  INFO,        0, , (Re)Opening databases in single user mode without transaction logging.
WCCILdata    (0), 2020.02.16 11:00:13.556, SYS,  INFO,        0, , Initialize archive smoothing
WCCILdata    (0), 2020.02.16 11:00:13.560, SYS,  INFO,        0, , Initialize archive smoothing
WCCILdata    (0), 2020.02.16 11:00:13.565, SYS,  INFO,        0, , Loading DpIdentification
WCCILdata    (0), 2020.02.16 11:00:13.574, SYS,  INFO,        0, , Initializing last value cache
WCCILdata    (0), 2020.02.16 11:00:13.581, SYS,  INFO,        0, , Loading internal datapoints
WCCILdata    (0), 2020.02.16 11:00:13.596, SYS,  WARNING,    33, General error in Data Manager, DataManDpIntern, loadInternalDp, Internal DPE not found: _DataManager.DataBase.Check:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.597, SYS,  INFO,        0, , Initializing ID history
WCCILdata    (0), 2020.02.16 11:00:13.598, SYS,  INFO,        0, , Initializing Alert history
WCCILdata    (0), 2020.02.16 11:00:13.599, SYS,  INFO,        0, , Initializing Alert Class cache
WCCILdata    (0), 2020.02.16 11:00:13.620, SYS,  INFO,        6, Initialization by Data Manager finished
WCCILdata    (0), 2020.02.16 11:00:13.666, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.arNr:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.668, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.state:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.669, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.arType:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.670, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.arName:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.672, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.hostNameGet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.674, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.hostNameSet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.676, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.filePathGet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.677, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.filePathSet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.680, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.fileNameGet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.681, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.fileNameSet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.683, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.createArchive:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.684, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.forwardToRDB:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.686, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.error.errNum:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.687, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.error.errDp:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.688, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.error.errBit:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.690, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.error.errRead:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.691, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxDpElGet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.692, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxDpElSet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.698, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxValuesGet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.700, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxValuesSet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.702, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxFillPctGet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.703, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxFillPctSet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.705, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxHeapSizeGet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.706, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxHeapSizeSet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.708, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxCacheGet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.709, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxCacheSet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.711, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxCorrCacheGet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.713, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxCorrCacheSet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.714, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.intervals.aliveInterval:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.715, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.intervals.saveCycle:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.717, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.validFrom:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.718, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.validUntil:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.720, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.time:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.721, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.weekDay:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.723, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.monthDay:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.724, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.month:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.726, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.syncTime:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.731, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.syncWeekDay:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.734, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.syncDay:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.736, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.syncMonth:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.737, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.interval:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.739, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.delay:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.740, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.validFrom:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.742, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.validUntil:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.743, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.time:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.746, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.weekDay:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.747, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.monthDay:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.749, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.month:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.751, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.syncTime:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.752, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.syncWeekDay:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.754, SYS,  SEVERE,    118, Last error already repeated 50 times. Until another output occurs, this one will be blocked.
WCCILdata    (0), 2020.02.16 11:00:13.756, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileCompression.autoStartAfterSwitchSet:_original.._value
WCCILdata    (0), 2020.02.16 11:00:13.758, SYS,  INFO,      119, Last error repeated 213 times.
WCCILdata    (0), 2020.02.16 11:00:13.756, SYS,  INFO,        0, , Initializing Value Archives
WCCILdata    (0), 2020.02.16 11:00:13.763, SYS,  INFO,        0, , ValueArchive will be used...
WCCILdata    (0), 2020.02.16 11:00:14.605, SYS,  INFO,        4, Connected to (SYS: 1 Event -num 0 CONN: 1) @ na1r.services.adobe.com (127.0.0.1)
WCCILdata    (0), 2020.02.16 11:00:14.680, SYS,  INFO,        0, , Manager (SYS: 1 Event -num 0 CONN: 1) initialised
WCCILdata    (0), 2020.02.16 11:00:15.201, SYS,  INFO,        4, Connected to (SYS: 1 Driver -num 1 CONN: 1) @ na1r.services.adobe.com (127.0.0.1)
WCCILdata    (0), 2020.02.16 11:00:15.226, SYS,  INFO,        0, , Manager (SYS: 1 Driver -num 1 CONN: 1) initialised
WCCILdata    (0), 2020.02.16 11:00:15.661, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ na1r.services.adobe.com (127.0.0.1)
WCCILdata    (0), 2020.02.16 11:00:15.682, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2020.02.16 11:00:16.309, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2020.02.16 11:00:16.467, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ na1r.services.adobe.com (127.0.0.1)
WCCILdata    (0), 2020.02.16 11:00:16.490, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2020.02.16 11:00:17.075, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2020.02.16 11:00:17.286, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ na1r.services.adobe.com (127.0.0.1)
WCCILdata    (0), 2020.02.16 11:00:17.297, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2020.02.16 11:00:21.804, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2020.02.16 11:00:23.843, SYS,  INFO,       39, Connection lost, MAN: (SYS: 1 Driver -num 1 CONN: 1), Connection closed
WCCILdata    (0), 2020.02.16 11:00:25.950, SYS,  INFO,      181, Closing connection to (SYS: 1 Event -num 0 CONN: 1)
WCCILdata    (0), 2020.02.16 11:00:25.951, SYS,  INFO,       39, Connection lost, MAN: (SYS: 1 Event -num 0 CONN: 1), Connection closed
WCCILdata    (0), 2020.02.16 11:00:25.956, SYS,  INFO,        0, , Loading DpIdentification
WCCILdata    (0), 2020.02.16 11:00:25.995, SYS,  INFO,        2, Manager Stop
